#!/user/bin/env bash
# This is a comment: What is the OSI model?

2. The OSI model is a conceptual model that characterizes the communication functions of a telecommunication system without regard to their underlying internal structure and technology.
